import Testing
import Foundation
@testable import SwiftlyFeedbackKit

/// `QA-UNIT04-COMMENTS` `-10` — the Swift SDK's comment value type decodes the payload the
/// server actually sends.
///
/// The corpus this reads is **not** written here. It is generated by the server target's
/// `CommentWireContractTests` from the server's own `CommentResponseDTO` through the
/// server's own configured encoder, and that suite byte-diffs every committed copy —
/// including this one — against a fresh regeneration. A hand-written literal here would be
/// a second definition of the wire contract that drifts silently; the corpus plus the
/// diff gate is what makes this case a test of the *contract* rather than of a guess.
///
/// This replaces `testCommentModel`, which constructed a `Comment` and read two of the five
/// arguments it had just passed in — an assertion that could not fail for any product
/// reason.
///
/// ⚠️ The bare name `Comment` is ambiguous in this target: Swift Testing exports its own
/// `Comment` type. Every reference below is qualified `SwiftlyFeedbackKit.Comment`.
@Suite("CommentDecodeTests")
struct CommentDecodeTests {

    // MARK: - The corpus

    /// Repo-relative walk up from this file: `Tests/SwiftlyFeedbackKitTests/`.
    static var testsDirectory: URL {
        URL(fileURLWithPath: #filePath).deletingLastPathComponent()
    }

    static var corpusURL: URL {
        testsDirectory.appendingPathComponent("Fixtures/comment-wire-corpus.json")
    }

    static func corpusData() throws -> Data {
        try Data(contentsOf: corpusURL)
    }

    // MARK: - The decoder under test

    /// Replicates `APIClient`'s decoder configuration.
    ///
    /// `APIClient` holds its `JSONDecoder` as a `private let` inside an `actor`, so
    /// `@testable` cannot reach it and there is no way to decode *through* the shipped
    /// instance without either widening the SDK's public surface or booting a URL session.
    /// A replica is therefore unavoidable — and
    /// `theSDKConfiguresItsDecoderTheWayThisSuiteReplicates` reads `APIClient.swift` and
    /// asserts the two strategies still match, which is what keeps the replica a checked
    /// copy rather than a drifting second definition.
    ///
    /// Using a bare `JSONDecoder()` here would be the classic vacuous version of this test:
    /// it would decode nothing at all from a snake_case payload and the case would be red
    /// for a reason that has nothing to do with the SDK.
    static func sdkDecoder() -> JSONDecoder {
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        decoder.keyDecodingStrategy = .convertFromSnakeCase
        return decoder
    }

    // MARK: - -10

    /// `-10` — all five fields of both corpus entries, by value.
    ///
    /// Goes red on a `CodingKeys` drift, a date-strategy drift, or a renamed property. An
    /// admin entry and a non-admin entry are both asserted, so a decoder that hard-defaulted
    /// `isAdmin` in either direction cannot pass.
    @Test("The SDK's Comment decodes every field of the server's own corpus")
    func decodesTheServerCorpus() throws {
        let comments = try Self.sdkDecoder()
            .decode([SwiftlyFeedbackKit.Comment].self, from: Self.corpusData())

        #expect(comments.count == 2)

        let admin = try #require(comments.first)
        #expect(admin.id == UUID(uuidString: "11111111-1111-4111-8111-111111111111"))
        #expect(admin.content == "Thanks for the report - this ships in 2.4.")
        #expect(admin.userId == "fixture-admin-user")
        #expect(admin.isAdmin == true)
        #expect(admin.createdAt == Date(timeIntervalSince1970: 1_700_000_000))

        let user = comments[1]
        #expect(user.id == UUID(uuidString: "22222222-2222-4222-8222-222222222222"))
        #expect(user.content == "Please add dark mode.")
        #expect(user.userId == "fixture-end-user")
        #expect(user.isAdmin == false)
        #expect(user.createdAt == Date(timeIntervalSince1970: 1_700_003_600))
    }

    /// `-10` — array-element order is contractual and is asserted strictly.
    ///
    /// Object-*key* order is not contractual and nothing here compares bytes; element order
    /// is, because a list of comments rendered out of order is a visible defect.
    @Test("Corpus element order survives the decode")
    func preservesElementOrder() throws {
        let comments = try Self.sdkDecoder()
            .decode([SwiftlyFeedbackKit.Comment].self, from: Self.corpusData())

        #expect(comments.map(\.userId) == ["fixture-admin-user", "fixture-end-user"])
        #expect(comments.map(\.isAdmin) == [true, false])
    }

    /// `-10` — the replica decoder above matches the one the SDK ships.
    ///
    /// Without this, every assertion in this suite could be green over a decoder
    /// configuration the SDK abandoned.
    @Test("The SDK configures its decoder the way this suite replicates")
    func theSDKConfiguresItsDecoderTheWayThisSuiteReplicates() throws {
        let apiClient = Self.testsDirectory
            .deletingLastPathComponent()  // Tests
            .deletingLastPathComponent()  // SwiftlyFeedbackKit
            .appendingPathComponent("Sources/SwiftlyFeedbackKit/Networking/APIClient.swift")
        let source = try String(contentsOf: apiClient, encoding: .utf8)

        #expect(source.contains("self.decoder.dateDecodingStrategy = .iso8601"))
        #expect(source.contains("self.decoder.keyDecodingStrategy = .convertFromSnakeCase"))
    }

    /// Non-vacuity for the whole suite: the fixture on disk must be the real corpus, and the
    /// decode must be capable of failing.
    ///
    /// A `Fixtures/` directory that had been emptied, or a corpus whose admin entry had been
    /// flattened to `false`, would leave the assertions above green-looking and meaningless.
    @Test("The corpus fixture is present, is the server's shape, and can express a failure")
    func theCorpusIsNonVacuous() throws {
        let data = try Self.corpusData()
        #expect(data.count > 100)

        let raw = try #require(
            JSONSerialization.jsonObject(with: data) as? [[String: Any]]
        )
        #expect(raw.count == 2)
        #expect(Set(raw[0].keys) == ["id", "content", "user_id", "is_admin", "created_at"])

        // The admin flag genuinely differs between the two entries, so an implementation
        // that dropped it could not satisfy `decodesTheServerCorpus`.
        #expect(raw[0]["is_admin"] as? Bool == true)
        #expect(raw[1]["is_admin"] as? Bool == false)

        // A payload missing a required key must throw, so the green above is a decode that
        // ran rather than one that silently defaulted everything.
        let truncated = Data(#"[{"content":"x","user_id":"y","is_admin":false}]"#.utf8)
        #expect(throws: (any Error).self) {
            try Self.sdkDecoder().decode([SwiftlyFeedbackKit.Comment].self, from: truncated)
        }
    }
}
