import Foundation
import Testing
@testable import SwiftlyFeedbackKit

/// `QA-UNIT05-FEEDBACK` `-12`, Swift SDK consumer half — the SDK's `Feedback` decodes the
/// payload the **server actually sends**.
///
/// The corpus this reads is not written here. It is generated by the server target's
/// `FeedbackWireContractTests` from the server's own `FeedbackResponseDTO` through the
/// server's own configured encoder, and that suite byte-diffs this committed copy against a
/// fresh regeneration. A hand-written JSON literal here would be a second, drifting definition
/// of one wire contract — the exact defect `-12` exists to prevent.
///
/// **The SDK's `Feedback` is a deliberate subset of the DTO.** It carries none of the nine
/// integration links, no `total_mrr`, and no roadmap fields — an SDK embedded in a customer's
/// app has no business seeing an internal Linear URL or another customer's MRR. That subset is
/// asserted as a subset, which is why `-13`'s `…Url` casing half lives on the server and Admin
/// sides and not here: the SDK has no such property to mis-case.
@Suite struct FeedbackWireDecodeTests {

    /// Replicates `APIClient.init`'s decoder exactly — the one that runs on every SDK
    /// response. `theSDKClientInstallsTheStrategiesThisSuiteReplicates` reads the real file
    /// and asserts it still installs these two, which is what makes the replica a *checked*
    /// copy rather than a second definition.
    static func clientDecoder() -> JSONDecoder {
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        decoder.keyDecodingStrategy = .convertFromSnakeCase
        return decoder
    }

    static var corpusURL: URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .appendingPathComponent("Fixtures/feedback-wire-corpus.json")
    }

    static func corpusData() throws -> Data { try Data(contentsOf: corpusURL) }

    static let populatedID = UUID(uuidString: "11111111-1111-4111-8111-111111111111")!
    static let absentSyncStatesID = UUID(uuidString: "33333333-3333-4333-8333-333333333333")!
    static let mergedIntoID = UUID(uuidString: "44444444-4444-4444-8444-444444444444")!
    static let mergedChildID = UUID(uuidString: "55555555-5555-4555-8555-555555555555")!

    // MARK: - -12 · the decode

    /// `-12` — the whole corpus decodes into `[Feedback]` with the SDK's own decoder, and
    /// every field the SDK declares carries the server's value.
    ///
    /// Array-element order is contractual, so the entries are asserted positionally. The
    /// payload carries 41 keys and the SDK declares 17 of them; a `JSONDecoder` ignores the
    /// rest, which is the property that lets the server ship a field ahead of the SDK.
    @Test("-12 · The SDK's Feedback decodes every field it declares from the server's corpus")
    func theSDKDecodesTheServersOwnCorpus() throws {
        let items = try Self.clientDecoder().decode([Feedback].self, from: Self.corpusData())

        #expect(items.count == 3)

        let populated = items[0]
        #expect(populated.id == Self.populatedID)
        #expect(populated.title == "Add a dark theme")
        #expect(populated.description == "The list is hard to read at night.")
        #expect(populated.status == .inProgress)
        #expect(populated.category == .featureRequest)
        #expect(populated.userId == "fixture-end-user")
        #expect(populated.userEmail == "fixture-user@example.invalid")
        #expect(populated.voteCount == 7)
        #expect(populated.hasVoted == true)
        #expect(populated.commentCount == 3)
        #expect(populated.createdAt == Date(timeIntervalSince1970: 1_700_000_000))
        #expect(populated.updatedAt == Date(timeIntervalSince1970: 1_700_003_600))
        #expect(populated.mergedIntoId == Self.mergedIntoID)
        #expect(populated.mergedAt == Date(timeIntervalSince1970: 1_700_007_200))
        #expect(populated.mergedFeedbackIds == [Self.mergedChildID])
        #expect(populated.rejectionReason == "Superseded by the theming epic.")
        #expect(populated.isHiddenOverLimit == true)
        #expect(populated.isMerged == true)
    }

    /// `-12` — the sparse entry decodes too, with every optional `nil`.
    ///
    /// Paired with the populated case deliberately. A client that hard-requires `user_email`,
    /// `updated_at` or `merged_into_id` breaks on **every freshly-submitted item**, and only
    /// this half sees it: the populated entry carries all of them.
    @Test("-12 · The sparse corpus entry decodes with every optional nil")
    func theSparseEntryDecodesWithEveryOptionalNil() throws {
        let items = try Self.clientDecoder().decode([Feedback].self, from: Self.corpusData())
        let sparse = items[2]

        #expect(sparse.id == Self.absentSyncStatesID)
        #expect(sparse.status == .rejected)
        #expect(sparse.category == .other)
        #expect(sparse.userEmail == nil)
        #expect(sparse.mergedIntoId == nil)
        #expect(sparse.mergedAt == nil)
        #expect(sparse.mergedFeedbackIds == nil)
        #expect(sparse.rejectionReason == nil)
        #expect(sparse.isMerged == false)
        // Positive terminal signals, so this is not a green built from absences.
        #expect(sparse.title == "Crash on launch")
        #expect(sparse.voteCount == 0)
        // `updated_at` is present even on a never-edited row — FluentKit touches both the
        // .create and .update triggers on insert — so it is a positive here, not an absence.
        #expect(sparse.updatedAt == Date(timeIntervalSince1970: 1_700_003_600))
        #expect(sparse.isHiddenOverLimit == false)
    }

    /// `-12` — the corpus's `status` / `category` tokens reach the SDK's enums intact.
    ///
    /// The three entries carry three different statuses and three different categories, so
    /// this exercises more than one arm of each `RawRepresentable` init against the bytes the
    /// server really emits — a stronger claim than `-04`'s in-process round trip.
    @Test("-12 · Three different status and category tokens survive the wire")
    func threeDistinctEnumTokensSurviveTheWire() throws {
        let items = try Self.clientDecoder().decode([Feedback].self, from: Self.corpusData())

        #expect(items.map(\.status) == [.inProgress, .testflight, .rejected])
        #expect(items.map(\.category) == [.featureRequest, .bugReport, .other])
    }

    /// `-12` — the SDK's decoder configuration is the one this suite replicates.
    ///
    /// Without it every assertion above could be green over a strategy the client stopped
    /// using — and `.convertFromSnakeCase` is exactly the setting whose removal turns 41 wire
    /// keys into a `keyNotFound` on the first required field.
    @Test("-12 · APIClient still installs the strategies this suite replicates")
    func theSDKClientInstallsTheStrategiesThisSuiteReplicates() throws {
        let source = try WorkspaceSourceTree.sdkSource(
            "Sources/SwiftlyFeedbackKit/Networking/APIClient.swift"
        )

        #expect(source.contains("self.decoder.keyDecodingStrategy = .convertFromSnakeCase"))
        #expect(source.contains("self.decoder.dateDecodingStrategy = .iso8601"))
        #expect(source.contains("self.encoder.keyEncodingStrategy = .convertToSnakeCase"))
    }

    /// `-12` — non-vacuity for this whole file: the fixture on disk is the real corpus, it
    /// carries the keys the SDK ignores as well as the ones it reads, and it can express the
    /// failures the cases above claim to catch.
    ///
    /// A `Fixtures/` directory that had been emptied, or a corpus whose sparse entry had
    /// quietly gained a `user_email`, would leave every case above green and meaningless.
    @Test("-12 · The corpus fixture is present, is the server's shape, and can express a failure")
    func theCorpusFixtureIsTheRealOne() throws {
        let data = try Self.corpusData()
        let entries = try #require(
            JSONSerialization.jsonObject(with: data) as? [[String: Any]],
            "The feedback corpus is not a JSON array of objects."
        )

        #expect(entries.count == 3)
        // The populated entry carries the full 41-key server shape…
        #expect(entries[0].keys.count == 41)
        // …including keys the SDK deliberately does not declare.
        #expect(entries[0]["total_mrr"] != nil)
        #expect(entries[0]["github_issue_url"] != nil)
        #expect(entries[0]["sync_states"] != nil)
        // …and the sparse entry really is sparse, so the nil assertions above are reachable.
        #expect(entries[2]["user_email"] == nil)
        #expect(entries[2]["sync_states"] == nil)
        #expect(entries[2].keys.count == 13)
    }
}
